### ISSUE TITLE
Enhance Error Handling

### ISSUE THREAD

**Issue by mpark86** [jerryshueh/simple-noter#5]
```js
function saveNote(content) {
                fs.writeFile("/note", content, function (err) {
                    if (err) throw err;
                    else console.log("Document saved: " + content);
                });
            }
```
In the above code, since it's just throwing an error in case of the error, users might not know what happened if an error occurs. I think it might be a good idea to give some kind of notification to users instead of throwing err so that users are aware of what happened in case of an error.

**Comment by jerryshueh** [comment]
Great work noticing that bug Minuk! Thanks for tackling this issue!

**Comment by jerryshueh** [comment]
Hi Minuk, thanks for contributing via your pull request. I'd initially merged your code to the master, but realized that the pull request name and your branch name did not reflect the state of the project. Currently, this issue is #5. If you can re-submit your pull request with the proper name, I would really appreciate it! It's a small change, but it helps keep everything connected. Thank you!

**Comment by mpark86** [comment]
Oh you're right! Sorry about that. I wasn't aware of the closed issues. I'll fix it right now.

**Comment by mpark86** [comment]
Re-submitted the pull request!
